// import Introduction from '../docs/1.md';
// import NovaEarn from '../docs/3.md';
// import NovaAuction from '../docs/4.md';

import Earn from './Aspose.Words.895f1159-2aac-4bf4-8779-51d3028c6792.001.png';
import Supply from './Aspose.Words.895f1159-2aac-4bf4-8779-51d3028c6792.002.png';
import EarningRecord from './Aspose.Words.895f1159-2aac-4bf4-8779-51d3028c6792.003.png';
import Auction from './Aspose.Words.895f1159-2aac-4bf4-8779-51d3028c6792.004.png';
import Bid from './Aspose.Words.895f1159-2aac-4bf4-8779-51d3028c6792.005.png';

export const IntroductionMD = `# **Introduction to Nova**

## **What does Nova do?**

We give users the reins to their yield.

Nova is a permissionless yield-trading protocol where users can sell their token points for earnings.

There are 2 main parts to fully understand Pendle:

1. Sell points for daily earnings
    You can provide ezETH on Nova, and Nova will auction the points generated by ezeth, with the proceeds distributed to all depositors. You can withdraw both the principal and any accrued earnings at any time after one day deposit.
    So, forget your points and earn ezETH everyday！

2. Obtain points through auction
    You can use ezETH to participate in the auctions for ezpoints and elpoints, allowing you to acquire a large number of points directly without holding ezETH for an extended period
`;


export const NovaEarnMD = `# **Nova Earn**

## **Enabling Nova Earn**

To enable Nova Earn：

1. click the ‘earn’ button on the app：

    ![](${Earn})

2. Supply ezETH and begin earning：

    ![](${Supply})

## **About Nova Earn**

Nova will auction the points generated by the supply of ezETH. 90% of the ezETH acquired through the auction will be distributed among all depositors, and 10% will be allocated to the Nova Dao.(Currently, 100% earning will be distributed among all depositors)

You can check your earnings after each acution：

![](${EarningRecord})
`;


export const NovaAuctionMD = `
# **Nova Auction**

## **Enabling Nova Auction**

To enable Nova Auction：

1. click the 'Auction' button and choose the point type you want(You can auction ez points and el  points on Nova)：

    ![](${Auction})

2. After the auction starts, place a bid, and successful bids will earn you points.

    ![](${Bid})

## **About Nova Auction**

1. You can auction ez points or el points now.

2. The auction adopts blind bidding (you cannot know the bids of others, and likewise, others cannot know your bid).Confirm the bidding price and quantity, and proceed with the bidding.

3.  After the auction, the highest bidder wins. The final transaction price is the lowest price among the successful bidders, and Nova will refund the excess part.

For example, if the total auction is for 100 units, A purchases 50 units at a rate of 0.2 ezETH per unit, B purchases 50 units at a rate of 0.1 ezETH per unit, and C purchases 50 units at a rate of 0.05 ezETH per unit; A wins the bid and receives a refund of 5 ezETH (50 \* (0.2-0.1) ezETH), B wins the bid , while C fails in the bid and receives a refund of 2.5 ezETH (50 \* 0.05 ezETH).

`;
